version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run lint
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Quay Auth
          command: npm run test
workflows:
  version: 2
  workflow:
    jobs:
      - lint:
          context: Build
      - test:
          context: Build